{"version":"3.10.1","messages":["\nAn error occurred while loading ./spec/models/user_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  RSpec.describe User, type: :model do\u001b[0m\n\u001b[31m    it \"can be created successfully with valid data\" do\u001b[0m\n\u001b[31m      user = User.create(username: \"test_user\", password: \"sup3r-secret\", image_url: \"https://via.placeholder.com/150\", bio: \"bio\")\u001b[0m\n\u001b[31m      expect(user).to be_valid\u001b[0m\n\u001b[31m    end\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    it \"has many recipes\" do\u001b[0m\n\u001b[31m      expect(User.new).to respond_to(:recipes)\u001b[0m\n\u001b[31m    end\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mSyntaxError:\u001b[0m\n\u001b[31m  /Users/freddex/Development/code/phase-4/phase-4-rails-putting-it-all-together-auth/app/models/user.rb:6: syntax error, unexpected local variable or method, expecting `end'\u001b[0m\n\u001b[31m  ...word, presence: true uniqueness: true\u001b[0m\n\u001b[31m  ...                     ^~~~~~~~~~\u001b[0m\n\u001b[36m# /Users/freddex/.rvm/gems/ruby-2.7.4/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'\u001b[0m\n\u001b[36m# /Users/freddex/.rvm/gems/ruby-2.7.4/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'\u001b[0m\n\u001b[36m# ./spec/models/user_spec.rb:3:in `\u003ctop (required)\u003e'\u001b[0m\n"],"examples":[],"summary":{"duration":0.00017,"example_count":0,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":1},"summary_line":"0 examples, 0 failures, 1 error occurred outside of examples"}